name: tnotee
description: "A simple and convenient note-taking app"
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_markdown: ^0.6.18+3
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true